version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  service1:
    build: ./service1
    ports:
      - "50051:50051"
    depends_on:
      - rabbitmq
  service2:
    build: ./service2
    ports:
      - "50052:50052"
    depends_on:
      - rabbitmq
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
