#version: '3'
#
#services:
#  service1:
#    build:
#      context: ./microservice1
#      dockerfile: Dockerfile
#    container_name: service1
#    ports:
#      - "8001:8000"
#    environment:
#      - AMQP_URI=pyamqp://guest:guest@rabbitmq
#      - POSTGRES_DB=service1_db
#      - POSTGRES_USER=service1_user
#      - POSTGRES_PASSWORD=service1_pass
#      - REDIS_HOST=service1_redis
#    depends_on:
#      - rabbitmq
#      - service1_db
#      - service1_redis
#
#  service1_db:
#    image: postgres:13
#    container_name: service1_db
#    environment:
#      POSTGRES_DB: service1_db
#      POSTGRES_USER: service1_user
#      POSTGRES_PASSWORD: service1_pass
#    ports:
#      - "5433:5432"
#
#  service1_redis:
#    image: redis:6
#    container_name: service1_redis
#    ports:
#      - "6381:6379"
#
#  service2:
#    build:
#      context: ./microservice2
#      dockerfile: Dockerfile
#    container_name: service2
#    ports:
#      - "8002:8000"
#    environment:
#      - AMQP_URI=pyamqp://guest:guest@rabbitmq
#      - POSTGRES_DB=service2_db
#      - POSTGRES_USER=service2_user
#      - POSTGRES_PASSWORD=service2_pass
#      - REDIS_HOST=service2_redis
#    depends_on:
#      - rabbitmq
#      - service2_db
#      - service2_redis
#
#  service2_db:
#    image: postgres:13
#    container_name: service2_db
#    environment:
#      POSTGRES_DB: service2_db
#      POSTGRES_USER: service2_user
#      POSTGRES_PASSWORD: service2_pass
#    ports:
#      - "5434:5432"
#
#  service2_redis:
#    image: redis:6
#    container_name: service2_redis
#    ports:
#      - "6382:6379"
#
#  gateway:
#    build:
#      context: ./gateway
#      dockerfile: Dockerfile
#    container_name: gateway
#    ports:
#      - "8000:8000"
#    environment:
#      - AMQP_URI=pyamqp://guest:guest@rabbitmq
#    depends_on:
#      - rabbitmq
#      - service1
#      - service2
#
#  rabbitmq:
#    image: "rabbitmq:3-management"
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"

version: '3.7'

services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - service1
      - service2

  service1:
    build: ./service1
    ports:
      - "50051:50051"

  service2:
    build: ./service2
    ports:
      - "50052:50052"
