version: '3.8'

services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./service:/app
    environment:
      - DATABASE_URL=postgres://service1_user:service1_pass@service1_db/service1_db
      - REDIS_URL=redis://service1_redis:6379/0
    depends_on:
      - service1_db
      - service1_redis
      - rabbitmq
    deploy:
      replicas: 2

  service1_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: service1_db
      POSTGRES_USER: service1_user
      POSTGRES_PASSWORD: service1_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service1_redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
  redis_data:
