# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notif.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotif.proto\x12\x06nameko\"3\n\x0e\x45xampleRequest\x12\r\n\x05value\x18\x01 \x01(\t\x12\x12\n\nmultiplier\x18\x02 \x01(\x05\".\n\x0c\x45xampleReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05seqno\x18\x02 \x01(\x05\"(\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nnationalid\x18\x02 \x01(\t\"E\n\x15MessageToUsersRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1b\n\x05users\x18\x02 \x03(\x0b\x32\x0c.nameko.User\"%\n\x13MessageToUsersReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xe5\x02\n\x07\x65xample\x12=\n\x0bunary_unary\x12\x16.nameko.ExampleRequest\x1a\x14.nameko.ExampleReply\"\x00\x12@\n\x0cunary_stream\x12\x16.nameko.ExampleRequest\x1a\x14.nameko.ExampleReply\"\x00\x30\x01\x12@\n\x0cstream_unary\x12\x16.nameko.ExampleRequest\x1a\x14.nameko.ExampleReply\"\x00(\x01\x12\x43\n\rstream_stream\x12\x16.nameko.ExampleRequest\x1a\x14.nameko.ExampleReply\"\x00(\x01\x30\x01\x12R\n\x12SendMessageToUsers\x12\x1d.nameko.MessageToUsersRequest\x1a\x1b.nameko.MessageToUsersReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notif_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXAMPLEREQUEST']._serialized_start=23
  _globals['_EXAMPLEREQUEST']._serialized_end=74
  _globals['_EXAMPLEREPLY']._serialized_start=76
  _globals['_EXAMPLEREPLY']._serialized_end=122
  _globals['_USER']._serialized_start=124
  _globals['_USER']._serialized_end=164
  _globals['_MESSAGETOUSERSREQUEST']._serialized_start=166
  _globals['_MESSAGETOUSERSREQUEST']._serialized_end=235
  _globals['_MESSAGETOUSERSREPLY']._serialized_start=237
  _globals['_MESSAGETOUSERSREPLY']._serialized_end=274
  _globals['_EXAMPLE']._serialized_start=277
  _globals['_EXAMPLE']._serialized_end=634
# @@protoc_insertion_point(module_scope)
