# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notif.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotif.proto\x12\x06nameko\"I\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bnational_id\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"(\n\x11NationalIdRequest\x12\x13\n\x0bnational_id\x18\x01 \x01(\t\"\'\n\x08UserList\x12\x1b\n\x05users\x18\x01 \x03(\x0b\x32\x0c.nameko.User\"E\n\x15MessageToUsersRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1b\n\x05users\x18\x02 \x03(\x0b\x32\x0c.nameko.User\"\'\n\x13MessageToUsersReply\x12\x10\n\x08response\x18\x01 \x01(\t2\xa2\x01\n\x05notif\x12R\n\x12SendMessageToUsers\x12\x1d.nameko.MessageToUsersRequest\x1a\x1b.nameko.MessageToUsersReply\"\x00\x12\x45\n\x14GetUsersByNationalId\x12\x19.nameko.NationalIdRequest\x1a\x10.nameko.UserList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notif_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=23
  _globals['_USER']._serialized_end=96
  _globals['_NATIONALIDREQUEST']._serialized_start=98
  _globals['_NATIONALIDREQUEST']._serialized_end=138
  _globals['_USERLIST']._serialized_start=140
  _globals['_USERLIST']._serialized_end=179
  _globals['_MESSAGETOUSERSREQUEST']._serialized_start=181
  _globals['_MESSAGETOUSERSREQUEST']._serialized_end=250
  _globals['_MESSAGETOUSERSREPLY']._serialized_start=252
  _globals['_MESSAGETOUSERSREPLY']._serialized_end=291
  _globals['_NOTIF']._serialized_start=294
  _globals['_NOTIF']._serialized_end=456
# @@protoc_insertion_point(module_scope)
